In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabulary size
voc_size = 10000

In [24]:
## One Hot Representation
one_hot_rep = [one_hot(words, voc_size) for words in sent]
one_hot_rep


[[3027, 8603, 5419, 1581],
 [3027, 8603, 5419, 9551],
 [3027, 4698, 5419, 5089],
 [2661, 8561, 1980, 6904, 3970],
 [2661, 8561, 1980, 6904, 4269],
 [4637, 3027, 1171, 5419, 8574],
 [9263, 7513, 671, 6904]]

In [25]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [26]:
import numpy as np

In [33]:
import tensorflow as tf
print(tf.__version__)


2.18.0


In [27]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3027 8603 5419 1581]
 [   0    0    0    0 3027 8603 5419 9551]
 [   0    0    0    0 3027 4698 5419 5089]
 [   0    0    0 2661 8561 1980 6904 3970]
 [   0    0    0 2661 8561 1980 6904 4269]
 [   0    0    0 4637 3027 1171 5419 8574]
 [   0    0    0    0 9263 7513  671 6904]]


In [30]:
## Feature Representation
dim = 10

In [34]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
# Explicitly build the model
model.build(input_shape=(None, sent_length))
model.compile('adam', 'mse')

In [35]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


array([[[-0.03837768, -0.04666975,  0.01464912, -0.02338504,
         -0.03161167,  0.02152414, -0.03928982, -0.0019261 ,
         -0.029707  , -0.04913511],
        [-0.03837768, -0.04666975,  0.01464912, -0.02338504,
         -0.03161167,  0.02152414, -0.03928982, -0.0019261 ,
         -0.029707  , -0.04913511],
        [-0.03837768, -0.04666975,  0.01464912, -0.02338504,
         -0.03161167,  0.02152414, -0.03928982, -0.0019261 ,
         -0.029707  , -0.04913511],
        [-0.03837768, -0.04666975,  0.01464912, -0.02338504,
         -0.03161167,  0.02152414, -0.03928982, -0.0019261 ,
         -0.029707  , -0.04913511],
        [-0.02495573,  0.0295232 ,  0.01962575,  0.01144651,
         -0.01875322,  0.01157529, -0.01179174,  0.02269134,
         -0.02606602,  0.00155603],
        [ 0.02675131, -0.04772979,  0.00497975, -0.03071215,
          0.02268482,  0.02242197, -0.02566552, -0.02312137,
         -0.03566162, -0.00206097],
        [ 0.01756385,  0.00578602, -0.03087318,  0.0

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 3027, 8603, 5419, 1581], dtype=int32)